"""backref for courses and tags in Subject were flipped.

Revision ID: 5a1bf8e214a9
Revises: 781f8a31d49f
Create Date: 2022-02-25 18:56:23.405575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1bf8e214a9'
down_revision = '781f8a31d49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'unit', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    # ### end Alembic commands ###
