"""Added course_id column to unit to maintain link between unit and course

Revision ID: 6ff6301635bc
Revises: c8e619ebe78a
Create Date: 2022-02-21 10:26:56.132918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff6301635bc'
down_revision = 'c8e619ebe78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unit', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'course_id')
    # ### end Alembic commands ###
