"""empty message

Revision ID: 718903c7b257
Revises: 6ff6301635bc
Create Date: 2022-02-21 18:18:27.429067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718903c7b257'
down_revision = '6ff6301635bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
