"""empty message

Revision ID: d21d02f3f03f
Revises: 19b6ec12b716
Create Date: 2022-02-20 23:53:24.491701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21d02f3f03f'
down_revision = '19b6ec12b716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_url')
    # ### end Alembic commands ###
